platform :ios, ‘9.0’

target ‘JCElm’ do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    ‘RCTImage’,
    'DevSupport',    'RCTText',
    'RCTGeolocation',
    'BatchedBridge',
    'RCTNetwork',
    'RCTLinkingIOS',
    ‘RCTAnimation’,
    'RCTWebSocket',
  ]
  pod “yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end